var bingoList = [];
bingoList[1] = [
    {name: ".52 Gal", image: "s3-bingo/weapons/001.png"},
    {name: ".96 Gal", image: "s3-bingo/weapons/002.png"},
    {name: "Aerospray MG", image: "s3-bingo/weapons/003.png"},
    {name: "Ballpoint Splatling", image: "s3-bingo/weapons/004.png"},
    {name: "Bamboozler 14 Mk", image: "s3-bingo/weapons/005.png"},
    {name: "Blaster", image: "s3-bingo/weapons/006.png"},
    {name: "Bloblobber", image: "s3-bingo/weapons/007.png"},
    {name: "Carbon Roller", image: "s3-bingo/weapons/008.png"},
    {name: "Clash Blaster", image: "s3-bingo/weapons/009.png"},
    {name: "Squiffer", image: "s3-bingo/weapons/010.png"},
    {name: "Dapple Dualies", image: "s3-bingo/weapons/011.png"},
    {name: "Dark Tetra Dualies", image: "s3-bingo/weapons/012.png"},
    {name: "Dualie Squlechers", image: "s3-bingo/weapons/013.png"},
    {name: "Dynamo Roller", image: "s3-bingo/weapons/014.png"},
    {name: "E-liter 4K", image: "s3-bingo/weapons/015.png"},
    {name: "E-liter 4K Scope", image: "s3-bingo/weapons/016.png"},
    {name: "Exsplosher", image: "s3-bingo/weapons/017.png"},
    {name: "Flingza Roller", image: "s3-bingo/weapons/018.png"},
    {name: "Glooga Dualies", image: "s3-bingo/weapons/019.png"},
    {name: "Goo Tuber", image: "s3-bingo/weapons/020.png"},
    {name: "H-3 Nozzlenose", image: "s3-bingo/weapons/021.png"},
    {name: "Heavy Splatling", image: "s3-bingo/weapons/022.png"},
    {name: "Hero Shot Replica", image: "s3-bingo/weapons/023.png"},
    {name: "Hydra Splatling", image: "s3-bingo/weapons/024.png"},
    {name: "Inkbrush", image: "s3-bingo/weapons/025.png"},
    {name: "Jet Squelcher", image: "s3-bingo/weapons/026.png"},
    {name: "L-3 Nozzlenose", image: "s3-bingo/weapons/027.png"},
    {name: "Luna Blaster", image: "s3-bingo/weapons/028.png"},
    {name: "Mini Splatling", image: "s3-bingo/weapons/029.png"},
    {name: "N-ZAP '85", image: "s3-bingo/weapons/030.png"},
    {name: "Nautilus 47", image: "s3-bingo/weapons/031.png"},
    {name: "Octobrush", image: "s3-bingo/weapons/032.png"},
    {name: "Range Blaster", image: "s3-bingo/weapons/033.png"},
    {name: "Rapid Blaster", image: "s3-bingo/weapons/034.png"},
    {name: "Rapid Blaster Pro", image: "s3-bingo/weapons/035.png"},
    {name: "REEF-LUX 450", image: "s3-bingo/weapons/036.png"},
    {name: "Slosher", image: "s3-bingo/weapons/037.png"},
    {name: "Sloshing Machine", image: "s3-bingo/weapons/038.png"},
    {name: "Splash-o-matic", image: "s3-bingo/weapons/039.png"},
    {name: "Splat Brella", image: "s3-bingo/weapons/040.png"},
    {name: "Splat Charger", image: "s3-bingo/weapons/041.png"},
    {name: "Splat Dualies", image: "s3-bingo/weapons/042.png"},
    {name: "Splat Roller", image: "s3-bingo/weapons/043.png"},
    {name: "Splatana Stamper", image: "s3-bingo/weapons/044.png"},
    {name: "Splatana Wiper", image: "s3-bingo/weapons/045.png"},
    {name: "Splatterscope", image: "s3-bingo/weapons/046.png"},
    {name: "Splattershot", image: "s3-bingo/weapons/047.png"},
    {name: "Splattershot Jr.", image: "s3-bingo/weapons/048.png"},
    {name: "Splattershot Pro", image: "s3-bingo/weapons/049.png"},
    {name: "Sploosh-o-matic", image: "s3-bingo/weapons/050.png"},
    {name: "Squeezer", image: "s3-bingo/weapons/051.png"},
    {name: "Tenta Brella", image: "s3-bingo/weapons/052.png"},
    {name: "Tri-Slosher", image: "s3-bingo/weapons/053.png"},
    {name: "Tri-Stringer", image: "s3-bingo/weapons/054.png"},
    {name: "Undercover Brella", image: "s3-bingo/weapons/055.png"}
];

$(function() { srl.bingo(bingoList, 5, false); });